config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  root 'flights#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bookings, only: [:new, :create]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'

  validates :code, presence: true, uniqueness: true    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
  has_many :bookings
  has_many :passenger, through: :bookings
  
  validates :departure_airport, :arrival_airport, :start_datetime, :flight_duration, presence: true

  scope :departure_airport, ->(airport_id) { where(departure_airport_id: airport_id) }
  scope :arrival_airport, ->(airport_id) { where(arrival_airport_id: airport_id) }
  scope :passenger_count, ->(count) { where(passenger_count: count) }
  scope :flight_date, ->(date) { where("DATE(start_datetime) = ?", date) }

  attr_accessor :code
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings
  has_many :flights, through: :bookings
    
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    @passenger_count = params[:passenger_count].to_i

    @flights = Flight.all
    @flights_with_codes = @flights.map { |flight| [flight.code, flight.id] }
    @passenger = Passenger.all
  end

  def create
    @booking = Booking.find(booking_params)
    
    if @booking.save
      # Handle successful creation
      redirect_to new_booking_path, notice: 'Booking was successfully created'
    else
      # Handle creation failure
      render :new, status: :unprocessable_entity  
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, :passenger_id, :passenger_count)
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all
    @flights = Flight.all

    if params[:departure_airport_id].present?
      @flights = @flights.departure_airport(params[:departure_airport_id])
    end

    if params[:arrival_airport_id].present?
      @flights = @flights.arrival_airport(params[:arrival_airport_id])
    end

    if params[:passenger_count].present?
      @flights = @flights.passenger_count(params[:passenger_count].to_i)
    end

    if params[:flight_date].present?
      date = Date.parse(params[:flight_date].to_s)
      @flights = @flights.flight_date(date)
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  include ActionView::Helpers::DateHelper    
end

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<p>Selected Flight: <%= @flight.departure_airport.code %> to <%= @flight.arrival_airport.code %>, 
  <%= @flight.start_datetime %>, Duration: <%= @flight.flight_duration %>
</p>

<p>Number of Passengers: <%= @flight.passenger_count %></p>

<%= form_with(model: @booking, url: bookings_path) do |form| %>
  <div>
    <%= form.label :flight_id %>
    <%= form.select :flight_id, options_for_select(@flights_with_codes) %>
  </div>

  <div>
    <%= form.label :passenger_id %>
    <%= form.select :passenger_id, options_for_select(@passengers.map { |passenger| [passenger.name, passenger.id] }) %>
  </div>

  
  <div>
    <%= form.label :passenger_count %>
    <%= form.number_field :passenger_count, min: 1, max: 4 %>
  </div>
  <%= form.submit "Create Booking" %>
<% end %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= form_tag root_path, method: :get do %>
  <label for="departure_airport_id">Departure Airport:</label>    
  <%= select_tag 'departure_airport_id', 
  options_from_collection_for_select(@airports, :id, :code, params[:departure_airport_id]), include_blank: true %>

  <label for="arrival_airport_id">Arrival Airport:</label>
  <%= select_tag 'arrival_airport_id',
   options_from_collection_for_select(@airports, :id, :code, params[:arrival_airport_id]), include_blank: true %>

   <label for="passenger_count">Number of Passengers:</label>
   <%= select_tag 'passenger_count', options_for_select([1, 2, 3, 4], params[:passenger_count].to_i), include_blank: true %>

   <label for='flight_date'>Flight Date:</label>
   <%= select_date(Date.current, prefix: 'flight_date') %>

  <%= submit_tag 'Search' %>
<% end %> 

<br>

<!--<%# if @flights.any? %>
   <table>
   <thead>
       <tr>
       <th>Departure Airport</th>
       <th>Arrival Airport</th>
       <th>Start Datetime</th>
       <th>Flight Duration</th>
       </tr>
   </thead>
   <tbody>
       <%# @flights.each do |flight| %>
       <tr>  
           <td><%#= flight.departure_airport.code%></td>  
           <td><%#= flight.arrival_airport.code%></td> 
           <td><%#= flight.start_datetime %></td>
           <td><%#= flight.flight_duration %></td> 
       </tr>
       <%# end %>
   </tbody>
   </table>
<%# else %>
<p>No flights found matching the search criteria.</p>
<%# end %>-->

<% if @flights.any? %>
  <%= form_tag new_booking_path, method: :get do %>
    <% @flights.each do |flight| %>
      <label>
        <%= radio_button_tag 'flight_id', flight.id %>
        <%= "#{flight.departure_airport.code} to #{flight.arrival_airport.code},
            #{flight.start_datetime}, Duration: #{flight.flight_duration}, Passenger-count: #{flight.passenger_count}" %>
      </label>  
      <br>  
    <% end %> 
    <%= hidden_field_tag 'passenger_count', params[:passenger_count] %>  
    <%= submit_tag "Select" %>
  <% end %>
<% else %>
  <p>No flights found matching the search criteria.</p>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BearWindFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='container'>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %><br/>
      <%= yield %>
    </div>
  </body>
</html>